version: "3.9"
services:
    web:
        build: 
            context: .
            dockerfile: development.dockerfile
            
        image: spell-erp/spell-erp-dev-image
        ports:
            - "0.0.0.0:${EXPOSE_WEB_SERVER_PORT}:6000"
        volumes:
            - ./app:/code/app
            - ./config:/code/config
            - ./migrations:/code/migrations
            - ./scripts:/code/scripts
            - ./storage:/code/storage
        environment:
            APP_DEBUG: 'true'
            APP_SECRET_KEY: ${SECRET_KEY}

            DB_NAME: ${DB_NAME}
            DB_PASS: ${DB_PASS}
            DB_USER: root
            DB_HOST: db
            DB_PORT: 5432

            FORCE_SERVE_STATIC_FILES: ${FORCE_SERVE_STATIC_FILES}

        depends_on:
            - db

    db:
        image: postgres:13
        ports:
            - "127.0.0.1:${EXPOSE_DB_PORT}:5432"
        volumes:
            - ./data/postgresql:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /var/lib/postgresql/pgdata

    # db:
    #     image: mysql:8
    #     ports:
    #         - "9302:3306"
    #     volumes:
    #         - ./data/mysql:/var/lib/mysql
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_DATABASE: ${DB_NAME}
    #         MYSQL_ROOT_PASSWORD: ${DB_PASS}