version: "3.9"
services:
    web:
        image: spell-erp/spell-erp-image:latest
        volumes:
            - ./migrations:/code/migrations
            - ./storage:/code/storage
            - ./run:/code/run
        environment:
            APP_DEBUG: 'false'
            APP_SECRET_KEY: ${SECRET_KEY}
            
            DB_NAME: ${DB_NAME}
            DB_PASS: ${DB_PASS}
            DB_USER: root
            DB_HOST: db
            DB_PORT: 3306

            FORCE_SERVE_STATIC_FILES: ${FORCE_SERVE_STATIC_FILES}

            RUN_WORKERS: ${WEB_NUM_WORKERS}
            RUN_TYPE: ${WEB_RUN_TYPE}

        ports:
            - "${WEB_SERVER_PORT}:6000"

        depends_on:
            - db

    db:
        image: mysql:8
        volumes:
            - ./data/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}